## Hate Speech and Offensive Language Detection

In [1]:
import pandas as pd
import numpy as np

In [2]:
#importing the dataset
df = pd.read_csv("hatespeech.csv")

In [3]:
df.head(10)

count  hate_speech_count  offensive_language_count  neither_count  class  \
0      3                  0                         0              3      2   
1      3                  0                         3              0      1   
2      3                  0                         3              0      1   
3      3                  0                         2              1      1   
4      6                  0                         6              0      1   
5      3                  1                         2              0      1   
6      3                  0                         3              0      1   
7      3                  0                         3              0      1   
8      3                  0                         3              0      1   
9      3                  1                         2              0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  
5  !!!!!!!!!!!!!!!!!!"@T_Madison_x: The shit just...  
6  !!!!!!"@__BrighterDays: I can not just sit up ...  
7  !!!!&#8220;@selfiequeenbri: cause I'm tired of...  
8  " &amp; you might not get ya bitch back &amp; ...  
9  " @rhythmixx_ :hobbies include: fighting Maria...

In [4]:
df.shape

(24783, 6)

In [5]:
df.columns

Index(['count', 'hate_speech_count', 'offensive_language_count',
       'neither_count', 'class', 'tweet'],
      dtype='object')

In [6]:
df=df[['tweet','class']]

In [7]:
df

tweet  class
0      !!! RT @mayasolovely: As a woman you shouldn't...      2
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...      1
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...      1
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...      1
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...      1
...                                                  ...    ...
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...      1
24779  you've gone and broke the wrong heart baby, an...      2
24780  young buck wanna eat!!.. dat nigguh like I ain...      1
24781              youu got wild bitches tellin you lies      1
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...      2

[24783 rows x 2 columns]

### Data Pre-processing using NLTK Library

In [8]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [9]:
lemmatizer = WordNetLemmatizer()

In [11]:
import re
def preprocess(text):
  text = re.sub('[^a-zA-Z]', ' ',text)
  tokens = word_tokenize(text.lower())
  return " ".join(WordNetLemmatizer().lemmatize(word) for word in tokens if word not in stopwords.words('english'))

# Apply preprocessing
df['tweet'] = df["tweet"].apply(preprocess)

In [12]:
corpus = df['tweet'].tolist()

In [13]:
corpus[5]

'madison x shit blow claim faithful somebody still fucking hoe'

In [14]:
df

tweet  class
0      rt mayasolovely woman complain cleaning house ...      2
1      rt mleew boy dat cold tyga dwn bad cuffin dat ...      1
2      rt urkindofbrand dawg rt sbaby life ever fuck ...      1
3            rt c g anderson viva based look like tranny      1
4      rt shenikaroberts shit hear might true might f...      1
...                                                  ...    ...
24778  muthaf lie lifeasking pearl corey emanuel righ...      1
24779    gone broke wrong heart baby drove redneck crazy      2
24780  young buck wan na eat dat nigguh like aint fuc...      1
24781                     youu got wild bitch tellin lie      1
24782  ruffled ntac eileen dahlia beautiful color com...      2

[24783 rows x 2 columns]

### Converting text into numerical vector representations

In [15]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=50000) #setting the maximum number of words to be used to 50000 (most frequent)
tokenizer.fit_on_texts(corpus)
tokenized_tweet = tokenizer.texts_to_sequences(corpus)
vector =pad_sequences(tokenized_tweet, maxlen=30, padding='post')
word_index = tokenizer.word_index
vocab_size = len(tokenizer.word_index)+1

In [16]:
vocab_size

33166

In [17]:
vector

array([[    2, 11802,    97, ...,     0,     0,     0],
       [    2,  7670,    87, ...,     0,     0,     0],
       [    2,  5800,   656, ...,     0,     0,     0],
       ...,
       [  277,  1954,    63, ...,     0,     0,     0],
       [ 5495,     9,   860, ...,     0,     0,     0],
       [ 9980, 33161, 33162, ...,     0,     0,     0]], dtype=int32)

In [18]:
X=vector

In [21]:
Y = pd.get_dummies(df['class'], dtype=int).values
print('Shape of label tensor:', Y.shape)

Shape of label tensor: (24783, 3)


In [22]:
Y

array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       ...,
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
Y[50]

array([0, 1, 0])

In [24]:
df['tweet']

0        rt mayasolovely woman complain cleaning house ...
1        rt mleew boy dat cold tyga dwn bad cuffin dat ...
2        rt urkindofbrand dawg rt sbaby life ever fuck ...
3              rt c g anderson viva based look like tranny
4        rt shenikaroberts shit hear might true might f...
                               ...                        
24778    muthaf lie lifeasking pearl corey emanuel righ...
24779      gone broke wrong heart baby drove redneck crazy
24780    young buck wan na eat dat nigguh like aint fuc...
24781                       youu got wild bitch tellin lie
24782    ruffled ntac eileen dahlia beautiful color com...
Name: tweet, Length: 24783, dtype: object

In [25]:
y=np.array(Y)

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)

In [27]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [28]:
from tensorflow.keras.layers import Dropout, Bidirectional

embedding_vector_dim=50 ##features representation
model=Sequential()
model.add(Embedding(vocab_size,embedding_vector_dim,input_length=30))
model.add(Dropout(0.3))
model.add(Bidirectional(LSTM(50)))
model.add(Dropout(0.3))
#model.add(LSTM(50))
#model.add(Dropout(0.3))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 30, 50)            1658300   
                                                                 
 dropout (Dropout)           (None, 30, 50)            0         
                                                                 
 bidirectional (Bidirection  (None, 100)               40400     
 al)                                                             
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense (Dense)               (None, 3)                 303       
                                                                 
Total params: 1699003 (6.48 MB)
Trainable params: 1699003 (6.48 MB)
Non-trainable params: 0 (0.00 Byte)
__________________

In [30]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode='min', restore_best_weights=True)
model.fit(X_train, y_train, validation_split=0.33, epochs=10, batch_size=64, callbacks=[early_stopping])

Epoch 1/10
174/174 [==============================] - 20s 83ms/step - loss: 0.5763 - accuracy: 0.7958 - val_loss: 0.3473 - val_accuracy: 0.8849
Epoch 2/10
174/174 [==============================] - 15s 86ms/step - loss: 0.3015 - accuracy: 0.9021 - val_loss: 0.3230 - val_accuracy: 0.8980
Epoch 3/10
174/174 [==============================] - 12s 72ms/step - loss: 0.2152 - accuracy: 0.9230 - val_loss: 0.3584 - val_accuracy: 0.8874
Epoch 4/10
174/174 [==============================] - 12s 70ms/step - loss: 0.1480 - accuracy: 0.9532 - val_loss: 0.4470 - val_accuracy: 0.8765
Epoch 5/10
174/174 [==============================] - 12s 71ms/step - loss: 0.0912 - accuracy: 0.9711 - val_loss: 0.4753 - val_accuracy: 0.8619
Epoch 6/10
174/174 [==============================] - 13s 74ms/step - loss: 0.0537 - accuracy: 0.9841 - val_loss: 0.5278 - val_accuracy: 0.8666
Epoch 7/10
174/174 [==============================] - 13s 74ms/step - loss: 0.0353 - accuracy: 0.9885 - val_loss: 0.6240 - val_accuracy:

In [33]:
y_pred=model.predict(X_test)
y_pred=np.where(y_pred > 0.5, 1,0)
from sklearn.metrics import accuracy_score, classification_report
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy score : ", accuracy_score(y_test,y_pred))

256/256 [==============================] - 2s 7ms/step
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       465
           1       0.92      0.96      0.94      6335
           2       0.84      0.77      0.80      1379

   micro avg       0.91      0.87      0.89      8179
   macro avg       0.59      0.58      0.58      8179
weighted avg       0.85      0.87      0.86      8179
 samples avg       0.87      0.87      0.87      8179

Accuracy score :  0.8719892407384766


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
def predict_on_user_input():
  user_text = input("Enter your text: ")

  user_text = preprocess(user_text)

  # Tokenize the text
  tokens = user_text.split()

  # One-hot encode the tokens (assuming you have a word_index dictionary from training)
  encoded_sequence = [word_index.get(token, 0) for token in tokens]  # Map tokens to indices (0 for unknown words)
  padded_sequence = pad_sequences([encoded_sequence], maxlen=30, padding='post')

  # Prediction (optional)
  prediction = model.predict(padded_sequence)
  if prediction[0][0] > 0.5:
    print("Highly offensive and Hate speech detected")
  elif prediction[0][1] > 0.5:
    print("Hate speech detected")
  else:
    print("Positive")
  # ... (interpret and display the prediction)

predict_on_user_input()